#!/usr/bin/env python3
"""
GitHub Tech Digest Builder
Fetches trending Python repositories and generates a README digest.
"""

import requests
from datetime import datetime, timedelta


def get_trending_python_repos():
    """Query GitHub API for top 3 trending Python repos from last 7 days."""
    # Calculate date 7 days ago
    seven_days_ago = (datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d')
    
    # GitHub Search API endpoint
    url = "https://api.github.com/search/repositories"
    
    params = {
        'q': f'language:python created:>{seven_days_ago}',
        'sort': 'stars',
        'order': 'desc',
        'per_page': 3
    }
    
    headers = {
        'Accept': 'application/vnd.github.v3+json'
    }
    
    response = requests.get(url, params=params, headers=headers)
    response.raise_for_status()
    
    return response.json()['items']


def generate_readme(repos):
    """Generate README.md content from repository data."""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')
    
    readme = f"""# 🔥 GitHub Tech Digest - Trending Python Repositories

**Generated:** {timestamp}

This digest showcases the top 3 trending Python repositories created in the last 7 days, sorted by star count.

---

"""
    
    for i, repo in enumerate(repos, 1):
        name = repo['full_name']
        url = repo['html_url']
        stars = repo['stargazers_count']
        description = repo['description'] or 'No description provided'
        
        readme += f"""## {i}. [{name}]({url})

⭐ **Stars:** {stars:,}

📝 **Description:** {description}

---

"""
    
    readme += """
## About

This digest is automatically generated by the `build_digest.py` script, which queries the GitHub API for trending Python repositories.

**Repository:** [github-tech-digest](https://github.com/LandonMoran/github-tech-digest)
"""
    
    return readme


def main():
    print("Fetching trending Python repositories...")
    repos = get_trending_python_repos()
    
    print(f"Found {len(repos)} repositories")
    
    print("Generating README.md...")
    readme_content = generate_readme(repos)
    
    with open('README.md', 'w') as f:
        f.write(readme_content)
    
    print("✓ README.md generated successfully!")


if __name__ == '__main__':
    main()
